# Explore more

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

# Load the data

In [2]:
df = pd.read_csv('../module_2/data.csv')
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [3]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='str')

## Consistency in column names

In [4]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [5]:
df.columns

Index(['make', 'model', 'year', 'engine_fuel_type', 'engine_hp',
       'engine_cylinders', 'transmission_type', 'driven_wheels',
       'number_of_doors', 'market_category', 'vehicle_size', 'vehicle_style',
       'highway_mpg', 'city_mpg', 'popularity', 'msrp'],
      dtype='str')

In [6]:
df.head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

## Consistency in content for str
As we did for column names, we apply for the content of those which are str.

In [7]:
df.dtypes

make                     str
model                    str
year                   int64
engine_fuel_type         str
engine_hp            float64
engine_cylinders     float64
transmission_type        str
driven_wheels            str
number_of_doors      float64
market_category          str
vehicle_size             str
vehicle_style            str
highway_mpg            int64
city_mpg               int64
popularity             int64
msrp                   int64
dtype: object

In [8]:
strings = list(df.dtypes[df.dtypes == 'str'].index)
strings

['make',
 'model',
 'engine_fuel_type',
 'transmission_type',
 'driven_wheels',
 'market_category',
 'vehicle_size',
 'vehicle_style']

In [9]:
for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [10]:
df.head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,bmw,1_series_m,2011,premium_unleaded_(required),335.0,6.0,manual,rear_wheel_drive,2.0,"factory_tuner,luxury,high-performance",compact,coupe,26,19,3916,46135
1,bmw,1_series,2011,premium_unleaded_(required),300.0,6.0,manual,rear_wheel_drive,2.0,"luxury,performance",compact,convertible,28,19,3916,40650
2,bmw,1_series,2011,premium_unleaded_(required),300.0,6.0,manual,rear_wheel_drive,2.0,"luxury,high-performance",compact,coupe,28,20,3916,36350
3,bmw,1_series,2011,premium_unleaded_(required),230.0,6.0,manual,rear_wheel_drive,2.0,"luxury,performance",compact,coupe,28,18,3916,29450
4,bmw,1_series,2011,premium_unleaded_(required),230.0,6.0,manual,rear_wheel_drive,2.0,luxury,compact,convertible,28,18,3916,34500

In [11]:
df.dtypes

make                     str
model                    str
year                   int64
engine_fuel_type         str
engine_hp            float64
engine_cylinders     float64
transmission_type        str
driven_wheels            str
number_of_doors      float64
market_category          str
vehicle_size             str
vehicle_style            str
highway_mpg            int64
city_mpg               int64
popularity             int64
msrp                   int64
dtype: object

## Look at missing values

In [53]:
df.isnull().sum()

make                    0
model                   0
year                    0
engine_fuel_type        3
engine_hp              69
engine_cylinders       30
transmission_type       0
driven_wheels           0
number_of_doors         6
market_category      3742
vehicle_size            0
vehicle_style           0
highway_mpg             0
city_mpg                0
popularity              0
msrp                    0
dtype: int64

In [56]:
df = df.fillna(0)

In [57]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_fuel_type     0
engine_hp            0
engine_cylinders     0
transmission_type    0
driven_wheels        0
number_of_doors      0
market_category      0
vehicle_size         0
vehicle_style        0
highway_mpg          0
city_mpg             0
popularity           0
msrp                 0
dtype: int64

In [76]:
df

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,bmw,1_series_m,2011,premium_unleaded_(required),335.0,6.0,manual,rear_wheel_drive,2.0,"factory_tuner,luxury,high-performance",compact,coupe,26,19,3916,46135
1,bmw,1_series,2011,premium_unleaded_(required),300.0,6.0,manual,rear_wheel_drive,2.0,"luxury,performance",compact,convertible,28,19,3916,40650
2,bmw,1_series,2011,premium_unleaded_(required),300.0,6.0,manual,rear_wheel_drive,2.0,"luxury,high-performance",compact,coupe,28,20,3916,36350
3,bmw,1_series,2011,premium_unleaded_(required),230.0,6.0,manual,rear_wheel_drive,2.0,"luxury,performance",compact,coupe,28,18,3916,29450
4,bmw,1_series,2011,premium_unleaded_(required),230.0,6.0,manual,rear_wheel_drive,2.0,luxury,compact,convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,acura,zdx,2012,premium_unleaded_(required),300.0,6.0,automatic,all_wheel_drive,4.0,"crossover,hatchback,luxury",midsize,4dr_hatchback,23,16,204,46120
11910,acura,zdx,2012,premium_unleaded_(required),300.0,6.0,automatic,all_wheel_drive,4.0,"crossover,hatchback,luxury",midsize,4dr_hatchback,23,16,204,56670
11911,acura,zdx,2012,premium_unleaded_(required),300.0,6.0,automatic,all_wheel_drive,4.0,"crossover,hatchback,luxury",midsize,4dr_hatchback,23,16,204,50620
11912,acura,zdx,2013,premium_unleaded_(recommended),300.0,6.0,automatic,all_wheel_drive,4.0,"crossover,hatchback,luxury",midsize,4dr_hatchback,23,16,204,50920
11913,lincoln,zephyr,2006,regular_unleaded,221.0,6.0,automatic,front_wheel_drive,4.0,luxury,midsize,sedan,26,17,61,28995

In [79]:
df.dtypes

make                     str
model                    str
year                   int64
engine_fuel_type      object
engine_hp            float64
engine_cylinders     float64
transmission_type        str
driven_wheels            str
number_of_doors      float64
market_category       object
vehicle_size             str
vehicle_style            str
highway_mpg            int64
city_mpg               int64
popularity             int64
msrp                   int64
dtype: object

In [80]:
df["engine_fuel_type"] = df["engine_fuel_type"].astype(str)
df["market_category"] = df["market_category"].astype(str)

In [81]:
df.dtypes

make                     str
model                    str
year                   int64
engine_fuel_type         str
engine_hp            float64
engine_cylinders     float64
transmission_type        str
driven_wheels            str
number_of_doors      float64
market_category          str
vehicle_size             str
vehicle_style            str
highway_mpg            int64
city_mpg               int64
popularity             int64
msrp                   int64
dtype: object

# Setting up the validation framework
With Scikit-Learn

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [84]:
len(df_full_train), len(df_test)

(9531, 2383)

In [85]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [86]:
len(df_train), len(df_val), len(df_test)

(7148, 2383, 2383)

In [87]:
df_train.reset_index(drop=True)
df_val.reset_index(drop=True)
df_test.reset_index(drop=True)

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,lotus,evora_400,2017,premium_unleaded_(required),400.0,6.0,manual,rear_wheel_drive,2.0,"exotic,high-performance",compact,coupe,39,21,613,91900
1,aston_martin,v8_vantage,2014,premium_unleaded_(required),420.0,8.0,automated_manual,rear_wheel_drive,2.0,"exotic,high-performance",compact,convertible,21,14,259,136900
2,hyundai,genesis,2015,regular_unleaded,311.0,6.0,automatic,rear_wheel_drive,4.0,"luxury,performance",large,sedan,29,18,1439,38000
3,suzuki,samurai,1993,regular_unleaded,66.0,4.0,manual,four_wheel_drive,2.0,0,compact,convertible_suv,26,24,481,2000
4,mitsubishi,outlander,2015,regular_unleaded,166.0,4.0,automatic,all_wheel_drive,4.0,crossover,midsize,4dr_suv,29,24,436,26195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,mitsubishi,endeavor,2008,premium_unleaded_(required),225.0,6.0,automatic,all_wheel_drive,4.0,crossover,midsize,4dr_suv,19,15,436,29099
2379,bentley,continental_flying_spur,2013,flex-fuel_(premium_unleaded_required/e85),552.0,12.0,automatic,all_wheel_drive,4.0,"exotic,flex_fuel,luxury,high-performance",large,sedan,19,11,520,184200
2380,kia,optima,2014,regular_unleaded,274.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,31,20,1720,35300
2381,lamborghini,aventador,2014,premium_unleaded_(required),700.0,12.0,automated_manual,all_wheel_drive,2.0,"exotic,high-performance",midsize,convertible,16,10,1158,441600
2382,toyota,prius_c,2016,regular_unleaded,99.0,4.0,automatic,front_wheel_drive,4.0,"hatchback,hybrid",compact,4dr_hatchback,46,53,2031,20360

In [88]:
y_train = df_train['msrp'].values
y_val = df_val['msrp'].values
y_test = df_test['msrp'].values

In [89]:
del df_train['msrp']
del df_val['msrp']
del df_test['msrp']

# Find most important features

In [90]:
global_msrp = df_full_train.msrp.mean()
global_msrp

np.float64(40761.23806526073)

In [91]:
from sklearn.metrics import mutual_info_score

In [92]:
def mutual_info_msrp_score(series):
    return mutual_info_score(series, df_full_train.msrp)

In [93]:
df_full_train.dtypes

make                     str
model                    str
year                   int64
engine_fuel_type         str
engine_hp            float64
engine_cylinders     float64
transmission_type        str
driven_wheels            str
number_of_doors      float64
market_category          str
vehicle_size             str
vehicle_style            str
highway_mpg            int64
city_mpg               int64
popularity             int64
msrp                   int64
dtype: object

In [94]:
df_full_train.columns

Index(['make', 'model', 'year', 'engine_fuel_type', 'engine_hp',
       'engine_cylinders', 'transmission_type', 'driven_wheels',
       'number_of_doors', 'market_category', 'vehicle_size', 'vehicle_style',
       'highway_mpg', 'city_mpg', 'popularity', 'msrp'],
      dtype='str')

In [95]:
categorical = ['make', 'model', 'engine_fuel_type', 'transmission_type', 'driven_wheels', 'market_category', 'vehicle_size', 'vehicle_style']

In [96]:
numerical = ['year', 'engine_hp', 'engine_cylinders', 'number_of_doors', 'highway_mpg', 'city_mpg', 'popularity']

In [97]:
from IPython.display import display

In [98]:
for c in categorical:
    df_group = df_full_train.groupby(c).msrp.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_msrp
    df_group['risk'] = df_group['mean']/ global_msrp
    display(df_group)
    print()
    print()

                       mean  count          diff       risk
make
acura          3.476704e+04    195 -5.994197e+03   0.852944
alfa_romeo     6.273333e+04      3  2.197210e+04   1.539044
aston_martin   2.000792e+05     81  1.593179e+05   4.908565
audi           5.349082e+04    271  1.272958e+04   1.312296
bentley        2.456460e+05     60  2.048848e+05   6.026461
bmw            6.243973e+04    272  2.167849e+04   1.531841
bugatti        1.782951e+06      2  1.742190e+06  43.741336
buick          2.779391e+04    164 -1.296733e+04   0.681871
cadillac       5.553466e+04    318  1.477343e+04   1.362438
chevrolet      2.810167e+04    918 -1.265957e+04   0.689421
chrysler       2.665524e+04    153 -1.410600e+04   0.653936
dodge          2.231025e+04    496 -1.845099e+04   0.547340
ferrari        2.390576e+05     55  1.982964e+05   5.864827
fiat           2.344884e+04     43 -1.731240e+04   0.575273
ford           2.749526e+04    691 -1.326597e+04   0.674544
genesis        4.797500e+04      2  7.213762e+03   1.176976
gmc            3.039341e+04    401 -1.036782e+04   0.745645
honda          2.636275e+04    364 -1.439849e+04   0.646760
hummer         3.732500e+04     14 -3.436238e+03   0.915698
hyundai        2.491953e+04    237 -1.584171e+04   0.611354
infiniti       4.216342e+04    272  1.402177e+03   1.034400
kia            2.563866e+04    186 -1.512258e+04   0.628996
lamborghini    3.409756e+05     41  3.002144e+05   8.365193
land_rover     6.931118e+04    107  2.854994e+04   1.700419
lexus          4.831953e+04    165  7.558289e+03   1.185428
lincoln        4.271912e+04    127  1.957880e+03   1.048033
lotus          6.757577e+04     26  2.681453e+04   1.657844
maserati       1.108709e+05     49  7.010970e+04   2.720009
maybach        5.664321e+05     14  5.256709e+05  13.896343
mazda          1.996347e+04    321 -2.079777e+04   0.489766
mclaren        2.535312e+05      4  2.127700e+05   6.219910
mercedes-benz  7.107832e+04    281  3.031708e+04   1.743772
mitsubishi     2.101410e+04    182 -1.974714e+04   0.515541
nissan         2.842198e+04    450 -1.233925e+04   0.697280
oldsmobile     1.141531e+04    124 -2.934593e+04   0.280053
plymouth       3.145958e+03     71 -3.761528e+04   0.077180
pontiac        1.875400e+04    149 -2.200724e+04   0.460094
porsche        1.010679e+05    113  6.030671e+04   2.479511
rolls-royce    3.516219e+05     24  3.108606e+05   8.626379
saab           2.705743e+04     84 -1.370381e+04   0.663803
scion          1.993424e+04     46 -2.082700e+04   0.489049
spyker         2.149900e+05      2  1.742288e+05   5.274374
subaru         2.483671e+04    205 -1.592453e+04   0.609322
suzuki         1.822772e+04    277 -2.253352e+04   0.447183
tesla          8.454667e+04     15  4.378543e+04   2.074193
toyota         2.893663e+04    597 -1.182460e+04   0.709906
volkswagen     2.793691e+04    637 -1.282433e+04   0.685379
volvo          2.864756e+04    222 -1.211368e+04   0.702814

                     mean  count          diff      risk
model
100           2000.000000     13 -38761.238065  0.049066
124_spider   26895.000000      3 -13866.238065  0.659818
190-class     2000.000000      4 -38761.238065  0.049066
1_series     37989.285714     14  -2771.952351  0.931995
1_series_m   46135.000000      1   5373.761935  1.131835
...                   ...    ...           ...       ...
z4           58750.000000      6  17988.761935  1.441320
z4_m         51533.333333      3  10772.095268  1.264273
z8          129833.333333      3  89072.095268  3.185216
zdx          50970.000000      5  10208.761935  1.250453
zephyr       28995.000000      1 -11766.238065  0.711338

[899 rows x 4 columns]

,mean,count,diff,risk
engine_fuel_type,,,,
0,18632.333333,3,-22128.904732,0.457109
diesel,38616.552632,114,-2144.685434,0.947384
electric,47205.438596,57,6444.200531,1.158096
flex-fuel_(premium_unleaded_recommended/e85),49556.363636,22,8795.125571,1.215772
flex-fuel_(premium_unleaded_required/e85),163446.250000,40,122685.011935,4.009845
flex-fuel_(unleaded/e85),36309.586207,725,-4451.651858,0.890787
flex-fuel_(unleaded/natural_gas),38901.000000,5,-1860.238065,0.954363
natural_gas,29390.000000,1,-11371.238065,0.721028
premium_unleaded_(recommended),40778.510870,1196,17.272804,1.000424
premium_unleaded_(required),102257.581139,1633,61496.343074,2.508697
regular_unleaded,22914.089276,5735,-17847.148789,0.562154

                           mean  count          diff      risk
transmission_type
automated_manual   99320.821429    504  58559.583363  2.436649
automatic          41204.148733   6589    442.910667  1.010866
direct_drive       47205.438596     57   6444.200531  1.158096
manual             27156.956853   2364 -13604.281212  0.666245
unknown             3163.176471     17 -37598.061595  0.077603

                           mean  count          diff      risk
driven_wheels
all_wheel_drive    58543.146044   1883  17781.907978  1.436246
four_wheel_drive   35185.361037   1119  -5575.877029  0.863206
front_wheel_drive  23093.490289   3810 -17667.747777  0.566555
rear_wheel_drive   55498.344612   2719  14737.106547  1.361547

,mean,count,diff,risk
market_category,,,,
0,19978.739073,3020,-20782.498992,0.490141
crossover,30096.854671,867,-10664.383394,0.738369
"crossover,diesel",54155.000000,4,13393.761935,1.328591
"crossover,exotic,luxury,high-performance",83000.000000,1,42238.761935,2.036248
"crossover,exotic,luxury,performance",72000.000000,1,31238.761935,1.766384
...,...,...,...,...
"luxury,hybrid",55375.394737,38,14614.156672,1.358531
"luxury,performance",46442.817326,531,5681.579261,1.139387
"luxury,performance,hybrid",63462.857143,7,22701.619078,1.556941
performance,28359.810638,470,-12401.427427,0.695754
"performance,hybrid",31900.000000,1,-8861.238065,0.782606

                      mean  count          diff      risk
vehicle_size
compact       34397.725275   3822  -6363.512791  0.843883
large         54468.520993   2215  13707.282928  1.336282
midsize       39032.478535   3494  -1728.759531  0.957588

                             mean  count          diff      risk
vehicle_style
2dr_hatchback        16710.741117    394 -24050.496949  0.409966
2dr_suv              10804.053097    113 -29957.184968  0.265057
4dr_hatchback        22494.387543    578 -18266.850522  0.551857
4dr_suv              40385.206984   1976   -376.031081  0.990775
cargo_minivan        20815.593220     59 -19945.644845  0.510671
cargo_van            14762.148649     74 -25999.089417  0.362161
convertible          84756.815385    650  43995.577319  2.079348
convertible_suv      17021.240000     25 -23739.998065  0.417584
coupe                75851.402051    975  35090.163986  1.860871
crew_cab_pickup      37237.667290    535  -3523.570776  0.913556
extended_cab_pickup  22506.745020    502 -18254.493045  0.552160
passenger_minivan    25785.518519    324 -14975.719547  0.632599
passenger_van        28762.766990    103 -11998.471075  0.705640
regular_cab_pickup   15865.507645    327 -24895.730420  0.389230
sedan                39692.675453   2428  -1068.562612  0.973785
wagon                25630.341880    468 -15130.896185  0.628792

In [99]:
df_full_train[categorical].dtypes

make                 str
model                str
engine_fuel_type     str
transmission_type    str
driven_wheels        str
market_category      str
vehicle_size         str
vehicle_style        str
dtype: object

In [100]:
df_full_train[categorical]

,make,model,engine_fuel_type,transmission_type,driven_wheels,market_category,vehicle_size,vehicle_style
2711,mercedes-benz,clk-class,premium_unleaded_(required),automatic,rear_wheel_drive,"luxury,high-performance",compact,coupe
333,nissan,370z,premium_unleaded_(required),manual,rear_wheel_drive,high-performance,compact,coupe
9377,gmc,sierra_1500,flex-fuel_(unleaded/e85),automatic,rear_wheel_drive,flex_fuel,large,extended_cab_pickup
939,porsche,911,premium_unleaded_(required),manual,all_wheel_drive,"luxury,high-performance",compact,convertible
5675,volkswagen,gti,premium_unleaded_(recommended),manual,front_wheel_drive,"hatchback,performance",compact,4dr_hatchback
...,...,...,...,...,...,...,...,...
7813,audi,q5,premium_unleaded_(required),automatic,all_wheel_drive,"crossover,luxury",midsize,4dr_suv
10955,toyota,tundra,regular_unleaded,automatic,four_wheel_drive,0,large,crew_cab_pickup
905,saab,900,regular_unleaded,manual,front_wheel_drive,"hatchback,luxury",compact,4dr_hatchback
5192,pontiac,g6,regular_unleaded,automatic,front_wheel_drive,0,midsize,coupe
235,chrysler,300m,premium_unleaded_(required),automatic,front_wheel_drive,performance,large,sedan

In [101]:
mi =df_full_train[categorical].apply(mutual_info_msrp_score)
mi.sort_values(ascending=False)

model                5.495685
make                 2.730584
market_category      2.276686
vehicle_style        1.690086
engine_fuel_type     0.965162
driven_wheels        0.945937
vehicle_size         0.754077
transmission_type    0.581254
dtype: float64

In [102]:
df_full_train[numerical].corrwith(df_full_train.msrp)

year                0.225401
engine_hp           0.648103
engine_cylinders    0.527243
number_of_doors    -0.125982
highway_mpg        -0.157651
city_mpg           -0.156620
popularity         -0.048147
dtype: float64

In [155]:
categorical_important = ['make', 'model', 'engine_fuel_type', 'transmission_type', 'market_category', 'vehicle_style']

In [156]:
numerical = ['year', 'engine_hp', 'engine_cylinders', 'number_of_doors', 'highway_mpg', 'city_mpg', 'popularity']

# One-hot encoding

In [157]:
from sklearn.feature_extraction import DictVectorizer

## Train dataset

In [158]:
train_dicts = df_train[categorical_important + numerical_important].to_dict(orient="records")

In [159]:
dv = DictVectorizer(sparse=False)

In [160]:
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [161]:
# do directily fit & transform
X_train = dv.fit_transform(train_dicts)
X_train

array([[6., 0., 0., ..., 1., 0., 0.],
       [6., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       ...,
       [4., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       [6., 0., 0., ..., 0., 0., 0.]], shape=(7148, 61))

In [162]:
X_train.shape

(7148, 61)

## Val dataset

In [163]:
val_dicts = df_val[categorical_important + numerical_important].to_dict(orient="records")

In [164]:
dv.fit(val_dicts)

DictVectorizer(sparse=False)

In [120]:
X_val = dv.transform(val_dicts)
X_val

array([[6.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        2.015e+03],
       [8.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        2.000e+03],
       [6.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        2.015e+03],
       ...,
       [4.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        2.013e+03],
       [8.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        2.015e+03],
       [8.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        2.008e+03]], shape=(2383, 135))

# Linear regression

In [130]:
from sklearn.linear_model import LinearRegression

In [131]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [135]:
y_pred = model.predict(X_val)

ValueError: X has 135 features, but LinearRegression is expecting 150 features as input.

In [ ]:
y_pred >= 0.5

In [ ]:
msrp_decision = y_pred >= 0.5
msrp_decision